// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkoTe8i3mEt3vSer_iIIQbk3t09cTxyFM',
    appId: '1:247013292550:web:177e1f27faaff46fe9e187',
    messagingSenderId: '247013292550',
    projectId: 'fir-deneme-d53b4',
    authDomain: 'fir-deneme-d53b4.firebaseapp.com',
    storageBucket: 'fir-deneme-d53b4.firebasestorage.app',
    measurementId: 'G-N02M95FEQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHh9ZmYrq6LeB3TvCt0WnGm_2yQRFNDUQ',
    appId: '1:247013292550:android:e819300e22444625e9e187',
    messagingSenderId: '247013292550',
    projectId: 'fir-deneme-d53b4',
    storageBucket: 'fir-deneme-d53b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsrzPyHAmD0RDgS3yN5mQ6rE50u6s_TJI',
    appId: '1:247013292550:ios:e1ad2933abe35bb1e9e187',
    messagingSenderId: '247013292550',
    projectId: 'fir-deneme-d53b4',
    storageBucket: 'fir-deneme-d53b4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsrzPyHAmD0RDgS3yN5mQ6rE50u6s_TJI',
    appId: '1:247013292550:ios:e1ad2933abe35bb1e9e187',
    messagingSenderId: '247013292550',
    projectId: 'fir-deneme-d53b4',
    storageBucket: 'fir-deneme-d53b4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkoTe8i3mEt3vSer_iIIQbk3t09cTxyFM',
    appId: '1:247013292550:web:29f4b842a6f02e07e9e187',
    messagingSenderId: '247013292550',
    projectId: 'fir-deneme-d53b4',
    authDomain: 'fir-deneme-d53b4.firebaseapp.com',
    storageBucket: 'fir-deneme-d53b4.firebasestorage.app',
    measurementId: 'G-EG6JH5QYNB',
  );
}
